/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package CafeOtomasyon;

import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;
import javax.swing.JOptionPane;

/**
 *
 * @author T470
 */
public class GirisFrame extends javax.swing.JFrame {

    /**
     * Creates new form GirisJFrame
     */
    public GirisFrame() {
        initComponents();
        tarihSaat();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Siparisler = new javax.swing.JButton();
        UrunEkle = new javax.swing.JButton();
        SiparisAl = new javax.swing.JButton();
        TumUrunler = new javax.swing.JButton();
        Raporlar = new javax.swing.JButton();
        UrunleriYonet = new javax.swing.JButton();
        Baslik = new javax.swing.JLabel();
        Saat = new javax.swing.JLabel();
        Tarih = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        ArkaPlan = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(900, 630));
        setPreferredSize(new java.awt.Dimension(1100, 675));
        setResizable(false);

        jPanel1.setMaximumSize(new java.awt.Dimension(900, 2147483647));
        jPanel1.setMinimumSize(new java.awt.Dimension(900, 630));
        jPanel1.setPreferredSize(new java.awt.Dimension(900, 630));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Siparisler.setBackground(new java.awt.Color(153, 77, 28));
        Siparisler.setFont(new java.awt.Font("Times New Roman", 1, 26)); // NOI18N
        Siparisler.setForeground(new java.awt.Color(0, 0, 0));
        Siparisler.setText("Siparişler");
        Siparisler.setBorder(null);
        Siparisler.setMaximumSize(new java.awt.Dimension(85, 28));
        Siparisler.setMinimumSize(new java.awt.Dimension(85, 28));
        Siparisler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SiparislerActionPerformed(evt);
            }
        });
        jPanel1.add(Siparisler, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 180, 60));

        UrunEkle.setBackground(new java.awt.Color(153, 77, 28));
        UrunEkle.setFont(new java.awt.Font("Times New Roman", 1, 26)); // NOI18N
        UrunEkle.setForeground(new java.awt.Color(0, 0, 0));
        UrunEkle.setText("Ürün Ekle");
        UrunEkle.setBorder(null);
        UrunEkle.setMaximumSize(new java.awt.Dimension(84, 28));
        UrunEkle.setMinimumSize(new java.awt.Dimension(84, 28));
        UrunEkle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UrunEkleActionPerformed(evt);
            }
        });
        jPanel1.add(UrunEkle, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, 180, 60));

        SiparisAl.setBackground(new java.awt.Color(153, 77, 28));
        SiparisAl.setFont(new java.awt.Font("Times New Roman", 1, 26)); // NOI18N
        SiparisAl.setForeground(new java.awt.Color(0, 0, 0));
        SiparisAl.setText("Sipariş Al");
        SiparisAl.setBorder(null);
        SiparisAl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SiparisAlActionPerformed(evt);
            }
        });
        jPanel1.add(SiparisAl, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 180, 60));

        TumUrunler.setBackground(new java.awt.Color(153, 77, 28));
        TumUrunler.setFont(new java.awt.Font("Times New Roman", 1, 26)); // NOI18N
        TumUrunler.setForeground(new java.awt.Color(0, 0, 0));
        TumUrunler.setText("Tüm Ürünler");
        TumUrunler.setBorder(null);
        TumUrunler.setMaximumSize(new java.awt.Dimension(84, 28));
        TumUrunler.setMinimumSize(new java.awt.Dimension(84, 28));
        TumUrunler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TumUrunlerActionPerformed(evt);
            }
        });
        jPanel1.add(TumUrunler, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 470, 180, 60));

        Raporlar.setBackground(new java.awt.Color(153, 77, 28));
        Raporlar.setFont(new java.awt.Font("Times New Roman", 1, 26)); // NOI18N
        Raporlar.setForeground(new java.awt.Color(0, 0, 0));
        Raporlar.setText("Raporlar");
        Raporlar.setBorder(null);
        Raporlar.setMaximumSize(new java.awt.Dimension(84, 28));
        Raporlar.setMinimumSize(new java.awt.Dimension(84, 28));
        Raporlar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RaporlarActionPerformed(evt);
            }
        });
        jPanel1.add(Raporlar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 550, 180, 60));

        UrunleriYonet.setBackground(new java.awt.Color(153, 77, 28));
        UrunleriYonet.setFont(new java.awt.Font("Times New Roman", 1, 26)); // NOI18N
        UrunleriYonet.setForeground(new java.awt.Color(0, 0, 0));
        UrunleriYonet.setText("Ürünleri Yönet");
        UrunleriYonet.setBorder(null);
        UrunleriYonet.setMaximumSize(new java.awt.Dimension(84, 28));
        UrunleriYonet.setMinimumSize(new java.awt.Dimension(84, 28));
        UrunleriYonet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UrunleriYonetActionPerformed(evt);
            }
        });
        jPanel1.add(UrunleriYonet, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 380, 180, 60));

        Baslik.setBackground(new java.awt.Color(204, 255, 255));
        Baslik.setFont(new java.awt.Font("Imprint MT Shadow", 1, 65)); // NOI18N
        Baslik.setForeground(new java.awt.Color(0, 0, 0));
        Baslik.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Baslik.setText("Sweet Cup");
        jPanel1.add(Baslik, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 1080, 90));

        Saat.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        Saat.setForeground(new java.awt.Color(255, 255, 255));
        Saat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Saat.setText("00:00:00");
        jPanel1.add(Saat, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 190, 110, -1));

        Tarih.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Tarih.setForeground(new java.awt.Color(255, 255, 255));
        Tarih.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Tarih.setText("Cumartesi , 16-03-2024");
        jPanel1.add(Tarih, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 220, -1, -1));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("PM");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 190, 30, 20));

        ArkaPlan.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        ArkaPlan.setForeground(new java.awt.Color(0, 0, 0));
        ArkaPlan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resimler/Giris.png"))); // NOI18N
        ArkaPlan.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(107, 74, 51), new java.awt.Color(248, 152, 49)));
        jPanel1.add(ArkaPlan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1090, 630));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1091, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void UrunEkleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UrunEkleActionPerformed
        new UrunEkleFrame().setVisible(true);
    }//GEN-LAST:event_UrunEkleActionPerformed

    private void SiparisAlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SiparisAlActionPerformed
        new SiparisAlFrame().setVisible(true);
    }//GEN-LAST:event_SiparisAlActionPerformed

    private void SiparislerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SiparislerActionPerformed
        new SiparisGoruntule().setVisible(true);
    }//GEN-LAST:event_SiparislerActionPerformed

    private void UrunleriYonetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UrunleriYonetActionPerformed
        new UrunleriYonetFrame().setVisible(true);
    }//GEN-LAST:event_UrunleriYonetActionPerformed

    private void TumUrunlerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TumUrunlerActionPerformed
        new TumUrunlerFrame().setVisible(true);
    }//GEN-LAST:event_TumUrunlerActionPerformed

    private void RaporlarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RaporlarActionPerformed
        new RaporlarFrame().setVisible(true);
    }//GEN-LAST:event_RaporlarActionPerformed

    private void tarihSaat() {
        new Thread(new Runnable() {
            @Override
            public void run() {
                while(true) {
                    try {
                        Thread.sleep(1000);// her saniye saat güncellemek için
                    } catch (Exception ex) {
                        JOptionPane.showMessageDialog(null, ex.getMessage());
                    }
                    Date tarih = new Date();
                    SimpleDateFormat saatFormati = new SimpleDateFormat("h:mm:ss aa");//saat bilgilerini biçimlendirmek için kullanılır.8:32:35 PM
                    SimpleDateFormat tarihFormati = new SimpleDateFormat("EEEE, yyyy-MM-dd", new Locale("tr", "TR"));//Pazartesi, 2024-05-01
                    String zaman = saatFormati.format(tarih);
                    Saat.setText(zaman.split(" ") [0]);
                    jLabel1.setText(zaman.split(" ") [1]);
                    Tarih.setText (tarihFormati.format(tarih));
                    
                    
                }
            }
            
        }).start();// Thread başlatır
    }
   


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ArkaPlan;
    private javax.swing.JLabel Baslik;
    private javax.swing.JButton Raporlar;
    private javax.swing.JLabel Saat;
    private javax.swing.JButton SiparisAl;
    private javax.swing.JButton Siparisler;
    private javax.swing.JLabel Tarih;
    private javax.swing.JButton TumUrunler;
    private javax.swing.JButton UrunEkle;
    private javax.swing.JButton UrunleriYonet;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
