/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package CafeOtomasyon;

import JavaKodları.AdminVeri;
import javax.swing.JOptionPane;

/**
 *
 * @author T470
 */
public class GirisYapFrame extends javax.swing.JFrame {

    /**
     * Creates new form GirisYapFrame
     */
    AdminVeri veri = new AdminVeri();
    int yatay, dikey;

    public GirisYapFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        GirisYap = new javax.swing.JLabel();
        Cikis = new javax.swing.JLabel();
        KullanıcıAdı = new javax.swing.JTextField();
        KullanıcıText = new javax.swing.JTextField();
        Sifre = new javax.swing.JTextField();
        Sifretext = new javax.swing.JPasswordField();
        Giris = new javax.swing.JButton();
        Iptal = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        arkaPlan = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        GirisYap.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        GirisYap.setForeground(new java.awt.Color(0, 0, 0));
        GirisYap.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        GirisYap.setText("GİRİŞ YAP");
        jPanel1.add(GirisYap, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 250, 40));

        Cikis.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        Cikis.setForeground(new java.awt.Color(255, 255, 255));
        Cikis.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Cikis.setText("X");
        Cikis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CikisMouseExited(evt);
            }
        });
        jPanel1.add(Cikis, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, 35, 34));

        KullanıcıAdı.setEditable(false);
        KullanıcıAdı.setBackground(new java.awt.Color(248, 152, 49));
        KullanıcıAdı.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        KullanıcıAdı.setForeground(new java.awt.Color(0, 0, 0));
        KullanıcıAdı.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        KullanıcıAdı.setText("Kullanıcı Adı");
        KullanıcıAdı.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KullanıcıAdıActionPerformed(evt);
            }
        });
        jPanel1.add(KullanıcıAdı, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 150, 34));

        KullanıcıText.setBackground(new java.awt.Color(255, 255, 255));
        KullanıcıText.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        KullanıcıText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        KullanıcıText.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(107, 74, 51), new java.awt.Color(248, 152, 49)));
        KullanıcıText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                KullanıcıTextKeyTyped(evt);
            }
        });
        jPanel1.add(KullanıcıText, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 192, 34));

        Sifre.setEditable(false);
        Sifre.setBackground(new java.awt.Color(248, 152, 49));
        Sifre.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Sifre.setForeground(new java.awt.Color(0, 0, 0));
        Sifre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Sifre.setText("Şifre");
        jPanel1.add(Sifre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 150, 34));

        Sifretext.setBackground(new java.awt.Color(255, 255, 255));
        Sifretext.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        Sifretext.setForeground(new java.awt.Color(0, 0, 0));
        Sifretext.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Sifretext.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(107, 74, 51), new java.awt.Color(248, 152, 49)));
        jPanel1.add(Sifretext, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 192, 34));

        Giris.setBackground(new java.awt.Color(153, 77, 28));
        Giris.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        Giris.setForeground(new java.awt.Color(0, 0, 0));
        Giris.setText("Giriş yap");
        Giris.setBorder(null);
        Giris.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Giris.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GirisActionPerformed(evt);
            }
        });
        jPanel1.add(Giris, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 100, 34));

        Iptal.setBackground(new java.awt.Color(153, 77, 28));
        Iptal.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        Iptal.setForeground(new java.awt.Color(0, 0, 0));
        Iptal.setText("İptal");
        Iptal.setBorder(null);
        Iptal.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(Iptal, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, 100, 34));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Henüz üye değil misiniz ? ");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Şifremi Unuttum");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 470, 160, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("ÜYE OL");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 440, -1, -1));

        arkaPlan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        arkaPlan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resimler/logo (10).png"))); // NOI18N
        jPanel1.add(arkaPlan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CikisMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CikisMouseExited
        setVisible(false);
    }//GEN-LAST:event_CikisMouseExited

    private void KullanıcıAdıActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KullanıcıAdıActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_KullanıcıAdıActionPerformed
// text alanına giriş yapıldığında
    private void KullanıcıTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_KullanıcıTextKeyTyped
        char giris = evt.getKeyChar();
        if (!(giris < '0' || giris > '9')) {
            evt.consume(); // kullanıcının girişi iptal olsun diye
            JOptionPane.showMessageDialog(this, "Sadece harf giriniz !", "Uyarı", 2); // 2=uyarı mesajı
        }
    }//GEN-LAST:event_KullanıcıTextKeyTyped
// mouse basıldığında işlemler
    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        yatay = evt.getX();
        dikey = evt.getY();
    }//GEN-LAST:event_jPanel1MousePressed
// mouse basılıyken mouse hareketi izlemek için
    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        int x = evt.getXOnScreen(); // ekrandaki yeri 
        int y = evt.getYOnScreen();
        this.setLocation(x - yatay, y - dikey); // yeni konum için
    }//GEN-LAST:event_jPanel1MouseDragged

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        new UyeOlFrame().setVisible(true);
        setVisible(false); // kayıt ol gözükmesin diye ekledim
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        new SifremiUnuttumFrame().setVisible(true);
        setVisible(false);

    }//GEN-LAST:event_jLabel2MouseClicked

    private void GirisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GirisActionPerformed
        if (bosMu()) {
            String kullaniciadi = KullanıcıText.getText().trim();
            String sifre = String.valueOf(Sifretext.getPassword());
            if (veri.AdminTablosuMaxSatir() != 1) {
                if (veri.giris(kullaniciadi, sifre)) {
                    JOptionPane.showMessageDialog(this, "Giriş başarılı.", "Giriş Başarılı",1);
                    new GirisFrame().setVisible(true);
                    setVisible(false);
                } else {
                    JOptionPane.showMessageDialog(this, "Kullanıcı adı veya şifre yanlış", "Giriş Başarısız", 2);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Yönetici bulunamadı !\n Önce üye olmalısınız.", "Giriş Başarısız", 2);
                new UyeOlFrame().setVisible(true);
                setVisible(false);
            }
    }//GEN-LAST:event_GirisActionPerformed
    }

    public boolean bosMu() {
        if (KullanıcıText.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Kullanıcı adı zorunludur.", "Uyarı", 2); // 2=uyarı mesajı
            return false;
        }
        if (String.valueOf(Sifretext.getPassword()).isEmpty()) {
            JOptionPane.showMessageDialog(this, "Şifre zorunludur.", "Uyarı", 2); // 2=uyarı mesajı
            return false;
        }
        return true;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GirisYapFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GirisYapFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GirisYapFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GirisYapFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GirisYapFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Cikis;
    private javax.swing.JButton Giris;
    private javax.swing.JLabel GirisYap;
    private javax.swing.JButton Iptal;
    private javax.swing.JTextField KullanıcıAdı;
    private javax.swing.JTextField KullanıcıText;
    private javax.swing.JTextField Sifre;
    private javax.swing.JPasswordField Sifretext;
    private javax.swing.JLabel arkaPlan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
