/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package CafeOtomasyon;

import JavaKodları.AdminVeri;
import java.awt.Color;
import javax.swing.JOptionPane;
import CafeOtomasyon.GirisYapFrame;

/**
 *
 * @author T470
 */
public class SifremiUnuttumFrame extends javax.swing.JFrame {

    /**
     * Creates new form SifremiUnuttumFrame
     */
    int yatay, dikey;
    Color kapali = new Color(204, 204, 204);
    Color acik = new Color(255, 255, 255);
    AdminVeri veri = new AdminVeri();

    public SifremiUnuttumFrame() {
        initComponents();
        GuvenlikS.setBackground(kapali);
        GuvenlikS.setEditable(false); // düzenlenemez
        Cevaptext.setBackground(kapali);
        Cevaptext.setEditable(false);
        SifreText.setBackground(kapali);
        SifreText.setEditable(false);
        Kaydet.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        SifreUnuttum = new javax.swing.JLabel();
        Cikis = new javax.swing.JLabel();
        ara = new javax.swing.JLabel();
        KullanıcıAdı = new javax.swing.JTextField();
        KullanıcıText = new javax.swing.JTextField();
        Sifre = new javax.swing.JTextField();
        SifreText = new javax.swing.JPasswordField();
        Guvenlik = new javax.swing.JTextField();
        GuvenlikS = new javax.swing.JTextField();
        Cevap = new javax.swing.JTextField();
        Cevaptext = new javax.swing.JTextField();
        Kaydet = new javax.swing.JButton();
        Geri = new javax.swing.JButton();
        arkaPlan = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SifreUnuttum.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        SifreUnuttum.setForeground(new java.awt.Color(0, 0, 0));
        SifreUnuttum.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SifreUnuttum.setText("ŞİFREMİ UNUTTUM");
        jPanel1.add(SifreUnuttum, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 250, 40));

        Cikis.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        Cikis.setForeground(new java.awt.Color(255, 255, 255));
        Cikis.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Cikis.setText("X");
        Cikis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CikisMouseExited(evt);
            }
        });
        jPanel1.add(Cikis, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, 35, 34));

        ara.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ara.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resimler/ara .png"))); // NOI18N
        ara.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                araMouseClicked(evt);
            }
        });
        jPanel1.add(ara, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 80, 30, 30));

        KullanıcıAdı.setEditable(false);
        KullanıcıAdı.setBackground(new java.awt.Color(248, 152, 49));
        KullanıcıAdı.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        KullanıcıAdı.setForeground(new java.awt.Color(0, 0, 0));
        KullanıcıAdı.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        KullanıcıAdı.setText("Kullanıcı Adı");
        KullanıcıAdı.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KullanıcıAdıActionPerformed(evt);
            }
        });
        jPanel1.add(KullanıcıAdı, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 150, 34));

        KullanıcıText.setBackground(new java.awt.Color(255, 255, 255));
        KullanıcıText.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        KullanıcıText.setForeground(new java.awt.Color(0, 0, 0));
        KullanıcıText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        KullanıcıText.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(107, 74, 51), new java.awt.Color(248, 152, 49)));
        jPanel1.add(KullanıcıText, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 192, 34));

        Sifre.setEditable(false);
        Sifre.setBackground(new java.awt.Color(248, 152, 49));
        Sifre.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Sifre.setForeground(new java.awt.Color(0, 0, 0));
        Sifre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Sifre.setText("Yeni Şifre");
        jPanel1.add(Sifre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 150, 34));

        SifreText.setBackground(new java.awt.Color(255, 255, 255));
        SifreText.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        SifreText.setForeground(new java.awt.Color(0, 0, 0));
        SifreText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        SifreText.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(107, 74, 51), new java.awt.Color(248, 152, 49)));
        jPanel1.add(SifreText, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, 192, 34));

        Guvenlik.setEditable(false);
        Guvenlik.setBackground(new java.awt.Color(248, 152, 49));
        Guvenlik.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Guvenlik.setForeground(new java.awt.Color(0, 0, 0));
        Guvenlik.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Guvenlik.setText("Güvenlik Sorusu");
        jPanel1.add(Guvenlik, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 150, 34));

        GuvenlikS.setBackground(new java.awt.Color(255, 255, 255));
        GuvenlikS.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        GuvenlikS.setForeground(new java.awt.Color(0, 0, 0));
        GuvenlikS.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        GuvenlikS.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(107, 74, 51), new java.awt.Color(248, 152, 49)));
        jPanel1.add(GuvenlikS, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 192, 34));

        Cevap.setEditable(false);
        Cevap.setBackground(new java.awt.Color(248, 152, 49));
        Cevap.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Cevap.setForeground(new java.awt.Color(0, 0, 0));
        Cevap.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Cevap.setText("Cevap");
        jPanel1.add(Cevap, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 150, 34));

        Cevaptext.setBackground(new java.awt.Color(255, 255, 255));
        Cevaptext.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        Cevaptext.setForeground(new java.awt.Color(0, 0, 0));
        Cevaptext.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Cevaptext.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(107, 74, 51), new java.awt.Color(248, 152, 49)));
        Cevaptext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CevaptextActionPerformed(evt);
            }
        });
        jPanel1.add(Cevaptext, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 192, 34));

        Kaydet.setBackground(new java.awt.Color(153, 77, 28));
        Kaydet.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        Kaydet.setForeground(new java.awt.Color(0, 0, 0));
        Kaydet.setText("Kaydet");
        Kaydet.setBorder(null);
        Kaydet.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Kaydet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KaydetActionPerformed(evt);
            }
        });
        jPanel1.add(Kaydet, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, 100, 34));

        Geri.setBackground(new java.awt.Color(153, 77, 28));
        Geri.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        Geri.setForeground(new java.awt.Color(0, 0, 0));
        Geri.setText("Geri");
        Geri.setBorder(null);
        Geri.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Geri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GeriActionPerformed(evt);
            }
        });
        jPanel1.add(Geri, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, 100, 34));

        arkaPlan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        arkaPlan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resimler/logo (10).png"))); // NOI18N
        jPanel1.add(arkaPlan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CikisMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CikisMouseExited
        setVisible(false);
    }//GEN-LAST:event_CikisMouseExited

    private void KullanıcıAdıActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KullanıcıAdıActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_KullanıcıAdıActionPerformed

    private void CevaptextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CevaptextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CevaptextActionPerformed

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        yatay = evt.getX();
        dikey = evt.getY();
    }//GEN-LAST:event_jPanel1MousePressed

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        int x = evt.getXOnScreen(); // ekrandaki yeri 
        int y = evt.getYOnScreen();
        this.setLocation(x - yatay, y - dikey); // yeni konum için
    }//GEN-LAST:event_jPanel1MouseDragged

    private void araMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_araMouseClicked
        if (KullanıcıText.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Kullanıcı adı zorunludur.", "Uyarı", 2);
        } else {
            if (veri.getSifre(KullanıcıText.getText())) {
                GuvenlikS.setBackground(acik);
                GuvenlikS.setEditable(true); // düzenlenebilir
                Cevaptext.setBackground(acik);
                Cevaptext.setEditable(true);
                SifreText.setBackground(acik);
                SifreText.setEditable(true);
                Kaydet.setEnabled(true);
            } else {
                JOptionPane.showMessageDialog(this, "Kullanıcı adı bulunamadı.", "Uyarı", 2);
            }
        }
    }//GEN-LAST:event_araMouseClicked

    private void KaydetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KaydetActionPerformed
        if (bosMu()) {
    String kullaniciadi = KullanıcıText.getText();
    String cevap = Cevaptext.getText();

    if (veri.getCevap(kullaniciadi, cevap)) {
        String yeniSifre = String.valueOf(SifreText.getPassword());
        String eskiSifre = String.valueOf(SifreText.getPassword());
        if (yeniSifre.equals(veri.getSifre(kullaniciadi))) {
            JOptionPane.showMessageDialog(this, "Yeni şifre eski şifrenizle aynı olamaz!", "Uyarı", 2);
        } else {
            veri.setSifre(kullaniciadi, yeniSifre);
            JOptionPane.showMessageDialog(this, "Şifre güncellendi.", "Mesaj", 1);
            new GirisYapFrame().setVisible(true);
            setVisible(false);
        }
    } else {
        JOptionPane.showMessageDialog(this, "Yanlış cevap girdiniz!", "Uyarı", 2);
    }
}

    }//GEN-LAST:event_KaydetActionPerformed

    private void GeriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GeriActionPerformed
        new GirisYapFrame().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_GeriActionPerformed

    public boolean bosMu() {
        if (String.valueOf(SifreText.getPassword()).isEmpty()) {
            JOptionPane.showMessageDialog(this, "Yeni şifre zorunludur.", "Uyarı", 2); // 2=uyarı mesajı
            return false;
        }
        if (Cevaptext.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Cevap zorunludur.", "Uyarı", 2); // 2=uyarı mesajı
            return false;
        }
        return true;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Cevap;
    private javax.swing.JTextField Cevaptext;
    private javax.swing.JLabel Cikis;
    private javax.swing.JButton Geri;
    private javax.swing.JTextField Guvenlik;
    public static javax.swing.JTextField GuvenlikS;
    private javax.swing.JButton Kaydet;
    private javax.swing.JTextField KullanıcıAdı;
    private javax.swing.JTextField KullanıcıText;
    private javax.swing.JTextField Sifre;
    public static javax.swing.JPasswordField SifreText;
    private javax.swing.JLabel SifreUnuttum;
    private javax.swing.JLabel ara;
    public static javax.swing.JLabel arkaPlan;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
