/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package CafeOtomasyon;

import JavaKodları.Veritabani;
import java.awt.Color;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author T470
 */
public class SiparisGoruntule extends javax.swing.JFrame {

    /**
     * Creates new form SiparisGörüntüle
     */
    int yatay, dikey;
    Veritabani veritabani = new Veritabani();
    DefaultTableModel model; //  tablo verilerini saklamak ve yönetmek için 
    Color renk = new Color(248, 152, 49);
    Color grid = new Color(153, 77, 28);

    public SiparisGoruntule() {
        initComponents();
        urunTablosu();

    }

    private void urunTablosu() {
        veritabani.getSiparisGoruntule(jTable1);
        model = (DefaultTableModel) jTable1.getModel();
        jTable1.setRowHeight(80);
        jTable1.setShowGrid(true);
        jTable1.setGridColor(Color.black);
        jTable1.setBackground(renk);
        jTable1.setSelectionBackground(grid);
        jTable1.setModel(model);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Tablo = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        cikis = new javax.swing.JLabel();
        arkaPlan = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setBackground(new java.awt.Color(255, 255, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sipariş Kodu", "Müşteri Adı", "Ürün Kodu", "Ürün Adı", "Toplam Ücret", "Sipariş Tarihi"
            }
        ));
        Tablo.setViewportView(jTable1);

        jPanel1.add(Tablo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 710, 460));

        cikis.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        cikis.setForeground(new java.awt.Color(255, 255, 255));
        cikis.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cikis.setText("X");
        cikis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cikisMouseClicked(evt);
            }
        });
        jPanel1.add(cikis, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 10, 35, 34));

        arkaPlan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resimler/SiparisGoruntule.png"))); // NOI18N
        jPanel1.add(arkaPlan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 630));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cikisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cikisMouseClicked
        setVisible(false);
    }//GEN-LAST:event_cikisMouseClicked

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        yatay = evt.getX();
        dikey = evt.getY();
    }//GEN-LAST:event_jPanel1MousePressed

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        int x = evt.getXOnScreen(); // ekrandaki yeri 
        int y = evt.getYOnScreen();
        this.setLocation(x - yatay, y - dikey); // yeni konum için
    }//GEN-LAST:event_jPanel1MouseDragged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane Tablo;
    private javax.swing.JLabel arkaPlan;
    private javax.swing.JLabel cikis;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
