/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package CafeOtomasyon;

import JavaKodları.Urun;
import JavaKodları.Veritabani;
import java.io.File;
import java.nio.file.Files;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author T470
 */
public class UrunEkleFrame extends javax.swing.JFrame {

    /**
     * Creates new form ÜrünEkleFrame
     */
    private File dosya;
    int yatay, dikey;
    Veritabani veritabani = new Veritabani();

    public UrunEkleFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ÜrünAdıtext = new javax.swing.JTextField();
        UrunAditext = new javax.swing.JTextField();
        Fiyat = new javax.swing.JTextField();
        FiyatText = new javax.swing.JTextField();
        Fiyat1 = new javax.swing.JTextField();
        ResimEkle = new javax.swing.JButton();
        Kaydet = new javax.swing.JButton();
        Cikis = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        ArkaPlan = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ÜrünAdıtext.setEditable(false);
        ÜrünAdıtext.setBackground(new java.awt.Color(248, 152, 49));
        ÜrünAdıtext.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        ÜrünAdıtext.setForeground(new java.awt.Color(0, 0, 0));
        ÜrünAdıtext.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ÜrünAdıtext.setText("Ürün Adı");
        jPanel1.add(ÜrünAdıtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 130, 40));

        UrunAditext.setBackground(new java.awt.Color(255, 255, 255));
        UrunAditext.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        UrunAditext.setForeground(new java.awt.Color(0, 0, 0));
        UrunAditext.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        UrunAditext.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(107, 74, 51), new java.awt.Color(248, 152, 49)));
        jPanel1.add(UrunAditext, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 214, 40));

        Fiyat.setEditable(false);
        Fiyat.setBackground(new java.awt.Color(248, 152, 49));
        Fiyat.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Fiyat.setForeground(new java.awt.Color(0, 0, 0));
        Fiyat.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Fiyat.setText("Fiyat");
        jPanel1.add(Fiyat, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 130, 40));

        FiyatText.setBackground(new java.awt.Color(255, 255, 255));
        FiyatText.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        FiyatText.setForeground(new java.awt.Color(0, 0, 0));
        FiyatText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        FiyatText.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(107, 74, 51), new java.awt.Color(248, 152, 49)));
        jPanel1.add(FiyatText, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 214, 40));

        Fiyat1.setEditable(false);
        Fiyat1.setBackground(new java.awt.Color(248, 152, 49));
        Fiyat1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Fiyat1.setForeground(new java.awt.Color(0, 0, 0));
        Fiyat1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Fiyat1.setText("Resim");
        jPanel1.add(Fiyat1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 130, 40));

        ResimEkle.setBackground(new java.awt.Color(153, 77, 28));
        ResimEkle.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        ResimEkle.setForeground(new java.awt.Color(0, 0, 0));
        ResimEkle.setText("Resim Ekle");
        ResimEkle.setBorder(null);
        ResimEkle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResimEkleActionPerformed(evt);
            }
        });
        jPanel1.add(ResimEkle, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 113, 40));

        Kaydet.setBackground(new java.awt.Color(153, 77, 28));
        Kaydet.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Kaydet.setForeground(new java.awt.Color(0, 0, 0));
        Kaydet.setText("Kaydet");
        Kaydet.setBorder(null);
        Kaydet.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Kaydet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KaydetActionPerformed(evt);
            }
        });
        jPanel1.add(Kaydet, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, 214, 40));

        Cikis.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        Cikis.setForeground(new java.awt.Color(255, 255, 255));
        Cikis.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Cikis.setText("X");
        Cikis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CikisMouseClicked(evt);
            }
        });
        jPanel1.add(Cikis, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 10, 35, 34));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 156, 200, 25));

        ArkaPlan.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        ArkaPlan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resimler/UrunEkle.png"))); // NOI18N
        jPanel1.add(ArkaPlan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 470));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CikisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CikisMouseClicked
        setVisible(false);
    }//GEN-LAST:event_CikisMouseClicked

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        yatay = evt.getX();
        dikey = evt.getY();
    }//GEN-LAST:event_jPanel1MousePressed

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        int x = evt.getXOnScreen(); // ekrandaki yeri 
        int y = evt.getYOnScreen();
        this.setLocation(x - yatay, y - dikey); // yeni konum için
    }//GEN-LAST:event_jPanel1MouseDragged

    private void ResimEkleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResimEkleActionPerformed
        JFileChooser resim = new JFileChooser(); // dosya seçimi için
        resim.setMultiSelectionEnabled(false); // tek dosya seçilsin diye
        if (resim.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) { // dosya seçildiyse
            this.dosya = resim.getSelectedFile(); // seçilen dosya
            jLabel1.setText("Resim Eklendi");
        }
    }//GEN-LAST:event_ResimEkleActionPerformed

    private void KaydetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KaydetActionPerformed
        try {
            Urun urun = new Urun();
            urun.setAd(UrunAditext.getText().trim());
            urun.setFiyat(Double.parseDouble(FiyatText.getText().trim()));
            urun.setResim(Files.readAllBytes(this.dosya.toPath()));//byte dizisini bir ürünün resmi olarak ayarlar 
            if (veritabani.urunEkle(urun)) {
                JOptionPane.showMessageDialog(null, "Ürün başarıyla eklendi.","Mesaj",1);// null=kullanıcının hareketinden bağımsız
                temizle();
            } else {
                JOptionPane.showMessageDialog(null, "Ürün eklenemedi!", "Uyarı", 2);
            }
        } catch (Exception e) {
             JOptionPane.showMessageDialog(null, "Ürün eklenemedi!", "Uyarı", 2);
        }
    }//GEN-LAST:event_KaydetActionPerformed

    private void temizle() {
        UrunAditext.setText(null);
        FiyatText.setText(null);
        jLabel1.setText(null);
        dosya = null;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ArkaPlan;
    private javax.swing.JLabel Cikis;
    private javax.swing.JTextField Fiyat;
    private javax.swing.JTextField Fiyat1;
    private javax.swing.JTextField FiyatText;
    private javax.swing.JButton Kaydet;
    private javax.swing.JButton ResimEkle;
    private javax.swing.JTextField UrunAditext;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField ÜrünAdıtext;
    // End of variables declaration//GEN-END:variables
}
