/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package CafeOtomasyon;

import JavaKodları.Admin;
import JavaKodları.AdminVeri;
import javax.swing.JOptionPane;

/**
 *
 * @author T470
 */
public class UyeOlFrame extends javax.swing.JFrame {

    /**
     * Creates new form UyeOl
     */
    AdminVeri veri = new AdminVeri();
    int yatay, dikey;

    public UyeOlFrame() {
        initComponents();
        IdText.setText(String.valueOf(veri.AdminTablosuMaxSatir()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Cikis = new javax.swing.JLabel();
        ÜyeOl = new javax.swing.JLabel();
        Id = new javax.swing.JTextField();
        IdText = new javax.swing.JTextField();
        KullanıcıAdı = new javax.swing.JTextField();
        KullanıcıText = new javax.swing.JTextField();
        Sifre = new javax.swing.JTextField();
        SifreText = new javax.swing.JPasswordField();
        Guvenlik = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        Cevap = new javax.swing.JTextField();
        Cevaptext = new javax.swing.JTextField();
        Kaydet = new javax.swing.JButton();
        Geri = new javax.swing.JButton();
        arkaPlan = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Cikis.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        Cikis.setForeground(new java.awt.Color(255, 255, 255));
        Cikis.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Cikis.setText("X");
        Cikis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CikisMouseExited(evt);
            }
        });
        jPanel1.add(Cikis, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, 35, 34));

        ÜyeOl.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        ÜyeOl.setForeground(new java.awt.Color(0, 0, 0));
        ÜyeOl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ÜyeOl.setText("ÜYE OL");
        jPanel1.add(ÜyeOl, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 120, 40));

        Id.setEditable(false);
        Id.setBackground(new java.awt.Color(248, 152, 49));
        Id.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Id.setForeground(new java.awt.Color(0, 0, 0));
        Id.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Id.setText("ID");
        jPanel1.add(Id, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 150, 34));

        IdText.setEditable(false);
        IdText.setBackground(new java.awt.Color(255, 255, 255));
        IdText.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        IdText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        IdText.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(107, 74, 51), new java.awt.Color(248, 152, 49)));
        IdText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IdTextActionPerformed(evt);
            }
        });
        jPanel1.add(IdText, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 192, 34));

        KullanıcıAdı.setEditable(false);
        KullanıcıAdı.setBackground(new java.awt.Color(248, 152, 49));
        KullanıcıAdı.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        KullanıcıAdı.setForeground(new java.awt.Color(0, 0, 0));
        KullanıcıAdı.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        KullanıcıAdı.setText("Kullanıcı Adı");
        KullanıcıAdı.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KullanıcıAdıActionPerformed(evt);
            }
        });
        jPanel1.add(KullanıcıAdı, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 150, 34));

        KullanıcıText.setBackground(new java.awt.Color(255, 255, 255));
        KullanıcıText.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        KullanıcıText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        KullanıcıText.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(107, 74, 51), new java.awt.Color(248, 152, 49)));
        KullanıcıText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                KullanıcıTextKeyTyped(evt);
            }
        });
        jPanel1.add(KullanıcıText, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 192, 34));

        Sifre.setEditable(false);
        Sifre.setBackground(new java.awt.Color(248, 152, 49));
        Sifre.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Sifre.setForeground(new java.awt.Color(0, 0, 0));
        Sifre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Sifre.setText("Şifre");
        jPanel1.add(Sifre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 150, 34));

        SifreText.setBackground(new java.awt.Color(255, 255, 255));
        SifreText.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        SifreText.setForeground(new java.awt.Color(0, 0, 0));
        SifreText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        SifreText.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(107, 74, 51), new java.awt.Color(248, 152, 49)));
        jPanel1.add(SifreText, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 192, 34));

        Guvenlik.setEditable(false);
        Guvenlik.setBackground(new java.awt.Color(248, 152, 49));
        Guvenlik.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Guvenlik.setForeground(new java.awt.Color(0, 0, 0));
        Guvenlik.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Guvenlik.setText("Güvenlik Sorusu");
        jPanel1.add(Guvenlik, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 150, 34));

        jComboBox1.setBackground(new java.awt.Color(255, 255, 255));
        jComboBox1.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(0, 0, 0));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "En sevdiğiniz yemek ?", "İlk işin neydi ?", "En sevdiğiniz renk nedir ?", "İlk evcil hayvanınızın adı ?" }));
        jComboBox1.setSelectedIndex(-1);
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, 192, 34));

        Cevap.setEditable(false);
        Cevap.setBackground(new java.awt.Color(248, 152, 49));
        Cevap.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Cevap.setForeground(new java.awt.Color(0, 0, 0));
        Cevap.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Cevap.setText("Cevap");
        jPanel1.add(Cevap, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 150, 34));

        Cevaptext.setBackground(new java.awt.Color(255, 255, 255));
        Cevaptext.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        Cevaptext.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Cevaptext.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(107, 74, 51), new java.awt.Color(248, 152, 49)));
        Cevaptext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CevaptextActionPerformed(evt);
            }
        });
        jPanel1.add(Cevaptext, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, 192, 34));

        Kaydet.setBackground(new java.awt.Color(153, 77, 28));
        Kaydet.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        Kaydet.setForeground(new java.awt.Color(0, 0, 0));
        Kaydet.setText("Kaydet");
        Kaydet.setBorder(null);
        Kaydet.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Kaydet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KaydetActionPerformed(evt);
            }
        });
        jPanel1.add(Kaydet, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, 100, 34));

        Geri.setBackground(new java.awt.Color(153, 77, 28));
        Geri.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        Geri.setForeground(new java.awt.Color(0, 0, 0));
        Geri.setText("Geri");
        Geri.setBorder(null);
        Geri.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Geri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GeriActionPerformed(evt);
            }
        });
        jPanel1.add(Geri, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 330, 100, 34));

        arkaPlan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        arkaPlan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resimler/logo (10).png"))); // NOI18N
        arkaPlan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(arkaPlan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CikisMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CikisMouseExited
        setVisible(false);
    }//GEN-LAST:event_CikisMouseExited

    private void KullanıcıAdıActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KullanıcıAdıActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_KullanıcıAdıActionPerformed

    private void IdTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IdTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IdTextActionPerformed

    private void CevaptextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CevaptextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CevaptextActionPerformed
// mouse basıldığında işlemler
    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        yatay = evt.getX();
        dikey = evt.getY();
    }//GEN-LAST:event_jPanel1MousePressed
// mouse basılıyken mouse hareketi izlemek için
    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        int x = evt.getXOnScreen(); // ekrandaki yeri 
        int y = evt.getYOnScreen();
        this.setLocation(x - yatay, y - dikey); // yeni konum için
    }//GEN-LAST:event_jPanel1MouseDragged
// text alanına giriş yapıldığında
    private void KullanıcıTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_KullanıcıTextKeyTyped
        char giris = evt.getKeyChar();
        if (!(giris < '0' || giris > '9')) {
            evt.consume(); // kullanıcının girişi iptal olsun diye
            JOptionPane.showMessageDialog(this, "Sadece harf giriniz !", "Uyarı", 2); // 2=uyarı mesajı
        }
    }//GEN-LAST:event_KullanıcıTextKeyTyped

    private void KaydetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KaydetActionPerformed
        if (bosMu()) {
            String kullaniciadi = KullanıcıText.getText().trim();
            if (veri.adminVarMi(kullaniciadi)) {
                Admin admin = new Admin();
                admin.setId(veri.AdminTablosuMaxSatir());
                admin.setKullaniciadi(kullaniciadi);
                admin.setSifre(String.valueOf(SifreText.getPassword()));
                admin.setGuvenlikSorusu(jComboBox1.getSelectedItem().toString());
                admin.setCevap(Cevaptext.getText().trim());

                if (veri.ekle(admin)) {
                    JOptionPane.showMessageDialog(this, "Yönetici başarıyla eklendi.","Mesaj",1);
                    new GirisYapFrame().setVisible(true); // kayıt ol ekranına yönlendirdim
                    setVisible(false);
                } else {
                    JOptionPane.showMessageDialog(this, "Yönetici eklenemedi!", "Uyarı", 2);
                }
            }else {
            JOptionPane.showMessageDialog(this, "Kullanıcı adı zaten kullanılıyor!", "Uyarı", 2);
        } 
        }
    }//GEN-LAST:event_KaydetActionPerformed
// Geri çıkmak için
    private void GeriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GeriActionPerformed
        new GirisYapFrame().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_GeriActionPerformed
    /**/
    public boolean bosMu() {
        if (KullanıcıText.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Kullanıcı adı zorunludur.", "Uyarı", 2); // 2=uyarı mesajı
            return false;
        }
        if (String.valueOf(SifreText.getPassword()).isEmpty()) {
            JOptionPane.showMessageDialog(this, "Şifre zorunludur.", "Uyarı", 2); // 2=uyarı mesajı
            return false;
        }
        if (jComboBox1.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(this, "Güvenlik sorusu zorunludur.", "Uyarı", 2); // 2=uyarı mesajı
            return false;
        }
        if (Cevaptext.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Cevap zorunludur.", "Uyarı", 2); // 2=uyarı mesajı
            return false;
        }
        return true;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UyeOlFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UyeOlFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UyeOlFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UyeOlFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UyeOlFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Cevap;
    private javax.swing.JTextField Cevaptext;
    private javax.swing.JLabel Cikis;
    private javax.swing.JButton Geri;
    private javax.swing.JTextField Guvenlik;
    private javax.swing.JTextField Id;
    private javax.swing.JTextField IdText;
    private javax.swing.JButton Kaydet;
    private javax.swing.JTextField KullanıcıAdı;
    private javax.swing.JTextField KullanıcıText;
    private javax.swing.JTextField Sifre;
    private javax.swing.JPasswordField SifreText;
    private javax.swing.JLabel arkaPlan;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel ÜyeOl;
    // End of variables declaration//GEN-END:variables
}
